### ISSUE TITLE
Kategorien für Alben

### ISSUE THREAD

**Issue by shelvis** [markocupic/gallery_creator#15]
Moin,
aller guten Dinge sind 3, aber ich dachte mir ich mache mal unterschiedliche Tickets auf, da es sich ja um unterschiedliche Dinge handelt, die nichts miteinander zu tun haben und auch unterschiedlichen Aufwand verursachen.

Wir erstellen zur Zeit für einen Sportverein eine Webseite. Hier haben die unterschiedlichen Sparten jeweils eigene Bereiche. Entsprechend sollen auf der Seite Galerien einer Sparte nur die Bildergalerien angezeigt werden, die zu dieser Sparte gehören.
Ich habe jetzt der Übersichtlichkeit wegen Dummy-Alben für jede Sparte angelegt und dann darunter jeweils die einzelnen Alben angelegt. Dabei musste ich für jedes Album das Inhaltselement auswählen, in dem es angezeigt werden soll.
Ich fände es praktisch, wenn ich hier stattdessen Kategorien hätte anlegen können und dann in den jeweiligen Inhaltselementen hätte auswählen können, das alle Alben der jeweiligen Kategorie angezeigt werden sollen.

Sollte dies bereits irgendwie möglich sein, so wäre ich für einen Hinweis, wie das geht, dankbar.
Ansonsten möchte ich das mal als Feature-Wunsch hier lassen.

**Comment by fr43nk** [comment]
Hallo,
wenn es diese Funktionalität gäbe wäre ich auch sehr dankbar. Es ist zwar schon eine gewisse Hilfe Unteralben anzulegen, mit Kategorien hat das leider trotzdem nichts zu tun.
Vor allem, wenn im laufe der Zeit weitere Alben hinzukommen, muss man immer noch zusätzlich den entsprechenden Inhalt auf der jeweiligen Seite auswählen.

**Comment by markocupic** [comment]
Hallo Shelvis
Könnte ich einbauen. Da es ein kommerzielles Projekt ist, wäre es schön, wenn ich als Entwickler auch einen kleinen Obolus erhalten würde ;-)
Liebe Grüsse
Marko
