### ISSUE TITLE
Formatierter Albumkommentar

### ISSUE THREAD

**Issue by fr43nk** [markocupic/gallery_creator#16]
Hallo,

eine vielleicht kleine Sache für Alben: Der Albumkommentar nimmt derzeit nur reinen Text. Es wäre gut, wenn man HTML Tags einfügen könnte oder der RichTextEditor aktiviert ist.

**Comment by markocupic** [comment]
Hallo fr43nk
Das ist über eine Contao typische DCA Anpassung updatesicher möglich.
Kannst du mit dieser Info etwas anfangen?
Lg Marko

**Comment by fr43nk** [comment]
Hi Marko,

ehrlich gesagt spontan nicht wirklich. Wo muss ich da was eintragen?

Danke

**Comment by markocupic** [comment]
Hallo fr43nk
In die system/config/dcaconfig.php schreibst du das hier.

```php
<?php

// Anpassung gallery_creator
if(TL_MODE == 'BE')
{
	$GLOBALS['TL_DCA']['tl_gallery_creator_albums']['fields']['comment']['eval']['rte'] = 'tinyMCE';
}

```

Weitere Hinweis zur dca-Anpassung findest du hier:
https://contao.org/de/manual/3.4/customizing-contao.html#konfiguration-anpassen

Liebe Grüsse
Marko

**Comment by markocupic** [comment]
die Shifttaste drücken und halten und dann Enter gibt einen geschützten Zeilenumbruch
```html
<!-- geschützter Zeilenumbruch-->
<p>bla<br>bla<br>bla</p>
```

**Comment by fr43nk** [comment]
Nein, ich meine folgendes:
Im Backend, TinyMCE:
`<p>bla</p>`
`<p>bla</p>`
wird im Frontend zu:
`<p>bla</p>`
`<br>`
`<p>bla</p>`

**Comment by markocupic** [comment]
aha! Habe verstanden. Problem behoben im neusten build.
Lg Marko

**Comment by fr43nk** [comment]
Super!
Vielen Dank. Es funktioniert.
(nutzt du Flattr? :smile:)

**Comment by markocupic** [comment]
Bis jetzt noch nicht. Ich nutze aber paypal. Wenn du etwas spenden möchtest, würde ich mich natürlich sehr freuen. m.cupic@gmx.ch 
Lg Marko
