### ISSUE TITLE
Sortieren nach - Auswahl wird nicht gespeichert.

### ISSUE THREAD

**Issue by profimedien** [markocupic/gallery_creator#17]
Unter Contao 3.2.12. kann man in einem Album die Sortierreihenfolge nicht speichern.
Wählt man z.b. "Dateiname aufsteigend" springt er nach Speichern auf "Individuelle Reihenfolge" zurück. Gallery Creator 4.8.0 ist installiert und eigentlich sollte es ja durch das Update 4.7 behoben worden sein.

Besten Dank für eine kurze Info.

**Comment by markocupic** [comment]
Unter Contao 3.4 funktioniert es. Habe es soeben getestet. Wählst du einen Sortiermodus und drückst auf Speichern wird das sorting Feld bei jedem Bild im entsprechenden Album neu gesetzt. Sortierts du z.B. nach "Dateiname absteigend" bekommt die Datei 
a_bild.jpg als sortig-value 10, 
b_bild.jpg als sorting value 20,
c_bild.jpg als sorting value 30, usw.
Das Resultat siehst du dann im Frontend. In den Albumeinstellungen springt der Wert auf "individuelle Reihenfolge". Das muss so sein.
Probiers mal aus. 
Lg Marko
