### ISSUE TITLE
Contao 3.2.16 mit Gallery Creator 4.8

### ISSUE THREAD

**Issue by nuun** [markocupic/gallery_creator#18]
Hallo Marko
Erst mal vielen Dank für deine grossartige Arbeit mit GalleryCreator. Grundsätzlich ein Supper Tool.
Leider habe ich ein Problem. Nachdem Datei-Upload-Probleme aufgetreten sind beim Gallery Creator, habe ich das Contao mal upgedatet von 3.2.7 auf 3.2.16 zudem habe ich die alte GC deinstalliert und die neue 4.8 über die Erweiterungsverwaltung installiert. Jetzt habe ich folgende Probleme:

1. GC erkennt die alten Alben nicht mehr - sind über 100... 
2. Wenn ich ein neues Album anlege erscheint die folgende Fehlermeldung "Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax "

Fragen: 
- Gibts da irgendwelche bekannte Probleme zwischen diesen Versionen?
- habe ich grundsätzlich was übersehen?
- Könntest du mir Unterstützung bieten für diese Probleme? Natürlich gegen Cash.

Viele Dank für deine Unterstützung
Herr nuun.

**Comment by markocupic** [comment]
Hallo nuun
Bitte schick mir doch eine email mit einem Link, wo ich den Fehler sehen kann. 
Meine Adresse: m.cupic@gmx.ch
Liebe Grüsse
Marko

**Comment by markocupic** [comment]
Hallo nuun
Gehe mal zurück auf gallery_creator version 4.7.0. 
Mach das Update über die Erweiterungsverwaltung aud sem Backend, damit die runonce.php auch ausgeführt wird.
Die Version 4.8.0 scheint mit contao 3.2 nciht zu laufen.
Liebe Grüsse
Marko

**Comment by nuun** [comment]
Super Marko. Ich werde das gerne Testen morgen! Ich meld mich dann nochmals! Thanks

**Comment by markocupic** [comment]
Halo nuun
Konntest du das Problem lösen? 
Lg Marko

**Comment by nuun** [comment]
Hallo Marko - danke für die Nachfrage. Ich stehe gard vor den Ferien und habe den Berg voll zu tun. Ich schaue mir das so bald als möglich an und melde mich wieder über diesen Kanal. Danke und bis bald. Herr Nuun :-)

**Comment by nuun** [comment]
Hallo Marko. Zurück aus den Ferien! Ich möchte mich gerne nochmals dem Problem annehmen. 
Ich wollte über die Erweiterungsverwaltung von 4.8 auf 4.7 downgraden - das geht aber nicht. Muss das manuell machen - oder habe ich was übersehen? Grüsse mr. nuun

**Comment by markocupic** [comment]
Hallo mr. nuun
Ok. Probier den downgrade über den Erweiterungskatalog (nicht Erweiterungsverwaltung). Und hier einfach nach gallery_creator suchen. Im unteren rechten Bereich kannst du unter andere Versionen auch ältere Versionen auswählen. Probier mal Version 4.7.0.
Liebe Grüsse
Marko

**Comment by nuun** [comment]
Hey Marko... Das hat gefunzt. (Hab gar nicht gewusst, dass man über die Erweiterungsverwaltung auch ältere Versionen installieren kann.. schon wieder was gelernt...) 
Die 4.7 funktioniert nun ganz gut - juhuuu! Ein Problem besteht aber noch. Beim Fileupload bringt er mir nun bei einigen Bildern "Possible fileupload attack!" also von 10 Bildern motzt er bei ca. 5 mit dieser Meldung. Kennst du dieses Phänomen? Vielen Dank für deinen Support! 
high-nuun

**Comment by markocupic** [comment]
Hallo nuun
Wie siehts aus, wenn du die Bilder über die Dateiverwaltung hochlädst? Kommt die Fehlermeldung dann auch? 
Lg Marko

**Comment by nuun** [comment]
Hallo Marko
Nein, der Upload über die Dateiverwaltung funktioniert ohne diese Meldung. Ok - der Kunde könnte den Upload auch über die Dateiverwaltung machen, nur dann hat er deine schöne Bild-Verkleinerungs-Funktion nicht dabei ;-) Was meinst du? Viele Grüsse nuun

**Comment by markocupic** [comment]
Tritt der Fehler auch auf, wenn die Bilder vor dem Upload nicht verkleinert werden? 
Lg Marko

**Comment by nuun** [comment]
Nein. "Possible fileupload attack" kommt auch wenn "Bilder vor dem Upload nicht skalieren" angewählt ist...

**Comment by nuun** [comment]
Hi Marko
Hattest Du mal die Möglichkeit, das nochmals anzuschauen? Denkst Du mit dem Contao Update auf 3.4.4 und der aktuellsten GC Version 4.8 könnte der Fehler mit dem "Possible fileupload attack" behoben werden?

**Comment by markocupic** [comment]
Ich glaube schwer, dass du mit der neusten Version das Problem nicht haben wirst.
lg Marko

**Comment by nuun** [comment]
Hi Marko... So ich habe nun 3.4.4 installiert und die GC 4.8. Leider besteht immer noch ein Upload Problem. 
- Beim Upload mit Java-Jumploader lädt er einfach nicht alle Dateien hoch obwohl im JavaApplet alles grün ist. Danach steht bei mehrerern Dateien "Datei xyz.jpg wurde nur teilweise hochgeladen!" 
- Beim gc_html5_uploader lädt er auch sauber hoch mit grünen Haken aber wenn ich auf zurück gehe meldet er auch bei ca. 50% der hochgeladenen Bilder "Die Datei xyz.jpg wurde nur teilweise hochgeladen!"
Das einzige das geht ist Dateien aus bestehenden Ordnern zu importieren. 
Hast du noch eine Idee? 
Kann ich beim GC Uploader nicht den ganz normalen "Standard-Uploader" verwenden - also nicht den "gc_html5_uploader"?
Schaade - wäre eine coole Extension...
Gruess nuun

**Comment by nuun** [comment]
Nachtrag: 
Ich habe gemerkt, dass ich generell eine Problem mit der Dropzone habe. Das heisst auch bei der normalen Dateiverwaltung kriege ich nicht alle Bilder hoch. Auch dort meint Contao: "Die Datei xyz.jpg wurde nur teilweise hochgeladen!"
Hmmm.... Idee?

**Comment by markocupic** [comment]
Hast du die Bilder mit einer Software verkleinert? 
Bei mir trat der Fehler auch schon auf, weil die Software hier nicht sauber gearbeitet hatte. 
Tritt der Fehler auch auf, wenn du Bilder original ab Kamera hochlädst? 
Lg marko

**Comment by nuun** [comment]
Ich habe jetzt einen Test gemacht mit den verschiedensten Bildern - direkt ab cam, vom netz, und irgendwo von meiner platte... und der Upload funktioniert bei allen Bildtypen nicht wirklich... ein paar werden hochgeladen ein paar nicht.... 
vor allem habe ich das Problem auch bei anderen Contao-Installationen... 
so ein sch...
lg nuun

**Comment by markocupic** [comment]
Hallo nuun
Ab und zu habe ich das auch, dass Dateien nicht vollständig hochgeladen werden. Unabhängig von gallery_creator, sprich auch mit der Dateiverwaltung und Dropzone. 
Ab Gallery_creator 4.8. nutze ich die Contao-Klasse FileUpload. Deshalb treten die Probleme an beiden Orten auf. Ich bin mir aber ziemlich sicher, dass das nicht mit Contao zusammenhängt, sondern das Problem irgendwo zwischen deinem Lokalen Gerät (Browser) und dem Server liegt. 
Weil Contao nutzt bei Fileuploads keine aussergewähnlichen Methoden.
Mach doch mal bei Leo ein Ticket. Evtl. haben andere auch das selbe Problem.

Es tut mir leid, dass ich dir nicht helfen kann.

Grüsse
Marko

**Comment by nuun** [comment]
Hi Marko
Danke Dir für deinen ausführlichen Support - werde mich mal bei Leo schlau machen - ok.
Machs gut und hau rein ;-)
Greets nuun

**Comment by nuun** [comment]
Hi Marko
Jetzt habe ich doch nochmals ne andere Frage... 
Beim GC Update sind alle Galerien (über 100) und Verknüpfungen zu den Bildern verloren gegangen. Die beiden DB Backups (vorher nacher) habe ich noch. Im alten Dump sind noch alle Alben und Bilder vorhanden. 

Kann ich einfach alle INSERTS ausführen in der neuen DB? z.B.

INSERT INTO `tl_gallery_creator_albums` VALUES ( 8, 0, 128, 1423232192, '1', 1423090800, 1, 'nuun gmbh', '', 'nuun-test', 0x6e75756e2d74657374, '', '29', 'a:1:{i:0;s:4:"1646";}', '', 0, 0, '1', NULL, '', NULL, 0, 0, 0x613a3 ... d7d7d, 2, 'custom' );

und:

INSERT INTO `tl_gallery_creator_pictures` VALUES ( 2595, 81, 230, 1421357650, '1', '', 'ETF003.jpg', 'files/Inhalte/Bilder/7 Bildergalerien/Aktivriege/2013/ETF/ETF003.jpg', '1', NULL, 1371679200, '', 0, 7, '', NULL, '' );

Funktioniert das oder hat da grundsätzlich in der Struktur was geändert?
Danke und en Gruess.

**Comment by markocupic** [comment]
Hallo nuun
Das sollte nicht passieren. Evtl. wurde nach dem Update die config/runonce.php nicht richtig ausgeführt.
Die Änderung von 4.7 auf 4.8 ist die, dass in tl_gallery_creator_pictures die file uuid dazugekommen ist. Das heisst, wenn du das Bild über das Filesystem im Backend in einen anderen Ordner kopierst, gallery_creator trotzdem noch funktioniert, weil die file-uuid nicht geändert hat.

Die runonce.php würde jetzt von jedem Bild die uuid suchen und im Feld  tl_gallery_creator_pictures.uuid abspeichern. Da ist bei dir was schief gelaufen. Wenn es klappt, würdest du zu jedem Bild auch eine grüne Meldung erhalten. 
Probier doch nochmals über die Erweiterungsverwaltung ein Update zu machen. Wenn die runonce nicht ausgeführt wird,dann 2. Möglichkeit:
Lade dir doch mal meine extension aus dem repo manuell runter und kopier die runonce.php in das config-Verzeichnis meiner Erweiterung. 
Nachher gehst du ins Backend und wählst Erweiterungsverwaltung. Oben rechts klickst du auf Datenbank aktualisieren.

Hinweis: Gelöscht wurde nichts. Es fehlen ziemlich sicher einfach die uuid Einträge in der Datenbank.

Ansonsten hier meine email-Adresse:
m.cupic@gmx.ch

Für mehr Hilfe bräuchte ich evtl. mal Backend-Zugriff.

Liebe Grüsse

Marko

**Comment by markocupic** [comment]
Wenn du sicher gehen willst, machst du ein Downgrade von gallery_creator auf 4.7 und spielst den alten dump wieder ein.

Lg Marko

**Comment by nuun** [comment]
Puhhh - nach einem Downgrade von GC konnte ich das alte Dump einspeisen. Danach Upgrade auf 4.8 und alle 10o Alben waren wieder da -juhee alles ok (ausser halt der Upload) - das passt jetzt! 
Vielen Dank Marko!

**Comment by markocupic** [comment]
Gerne geschehen. Da bin ich aber auch froh. Was ist beim ersten Mal schief gelaufen?
Hast du eine Ahnung?
Lg Marko

**Comment by nuun** [comment]
Ja :-) Ich glaube ich hatte GC deinstalliert und neu installiert... (schähm :-)

**Comment by markocupic** [comment]
Trotzdem merkwürdig. Die Datenbank hast du beim Deinstallieren ja nicht gelöscht, oder?
Ende gut, alles gut ;-)
Lg Marko

**Comment by nuun** [comment]
Hm ich denke ich hatte die DB aktualisiert als der GC deinstalliert war, dann hat er natürlich alle Tables rausgelöscht :-) na ja wie gesagt ende gut haldengut... :-)

**Comment by markocupic** [comment]
Aha! Dann wird's schwierig ;-)
Lg und viel Spass mit meiner Erweiterung
Marko
