### ISSUE TITLE
Meta Tags für Galerien

### ISSUE THREAD

**Issue by Flaschenzug** [markocupic/gallery_creator#19]
Habe einen Vorschlag für zukünftige Versionen.
Wie wäre es mit der Möglichkeit, Meta Tags für die Galerien anzulegen?
Besonders Title und Description wären sinnvoll für Suchmaschinen.

**Comment by markocupic** [comment]
Hallo Flaschenzug
Hab das mal umgesetzt. Kannst mal testen. Beachte auch den "gc_generateFrontendTemplate"-Hook!

https://github.com/markocupic/gallery_creator
Nach unten scrollen für die Erklärung!
Liebe Grüsse
Marko

**Comment by Flaschenzug** [comment]
Keywords und Description laufen, danke für die schnelle Umsetzung!

Der Titel der Galerie wird allerdings noch nicht ausgegeben.
Und ich würde auch die Keywords (falls möglich) komplett überschreiben, nicht die andren anfügen (kann aber auch sein, dass dies durch die SEO Erweiterung die ich installiert habe verursacht wird).

**Comment by markocupic** [comment]
Hallo Flaschenzug
schau dir mal den oben geposteten Link an. Hier siehst du, wie du den Seitentitel überschreiben kannst. Die Keywords lassen sich aus dem Modul raus nicht überschreiben. D.h. wenn du Artikel mit Keywords aud der selben Seite hast, werdem die nachträglich noch angehängt.
lg Marko

**Comment by Flaschenzug** [comment]
Leider ist mir nicht klar, wie ich den einsetzen soll ...
Muss ich die Datei anlegen? Oder gibt es diese und ich finde sie nur nicht?
