### ISSUE TITLE
4.8.0 Fehlerhafte Bildabstands-Auswahl: Einheit nicht mehr wählbar

### ISSUE THREAD

**Issue by TSTWebdesign** [markocupic/gallery_creator#20]
In Version 4.8.0 ist die Einheit für den Bildabstand nicht mehr wählbar.
Dies führt dazu, dass Alben und Bilder keinen Abstand mehr zueinander einhalten.
In der Version 4.7.0 hat es noch funktioniert.

![zwischenablage02](https://cloud.githubusercontent.com/assets/9497262/6094170/12798710-af1f-11e4-933d-d9213226f5b8.jpg)

**Comment by markocupic** [comment]
Das kann ich nicht reproduzieren. Welche contao Version nutzt du? 
Lg marko

**Comment by TSTWebdesign** [comment]
Setze die Version 3.3.5 ein.

**Comment by markocupic** [comment]
Diese Version ist noch nicht kompatibel zu gallery_creator 4.8.0.
Am besten machst du ein update des cores auf Version 3.4

Oder du machst ein downgrade von gallery_creator über den Erweiterungskatalog auf Version 4.7.

Liebe Grüsse

Marko

**Comment by TSTWebdesign** [comment]
Danke für den Hinweis. Nach dem Update auf contao 3.4.3 konnte ich Einheit auch wieder ausgewählt werden.
