### ISSUE TITLE
Rechte für Alben

### ISSUE THREAD

**Issue by yeli69** [markocupic/gallery_creator#21]
Hallo,

wie kann ich es anstellen, dass mehrere Mitarbeiter (keine Admins) Alben bearbeiten können?
Bislang geht das ja scheinbar nur, wenn ein Mitarbeiter der Besitzer des jeweiligen Albums ist.

**Comment by markocupic** [comment]
In den Backend-Einstellungen unter Gallery-Creator-Einstellungen
das Häckchen "Backend-Album-Protection aufheben" aktivieren.
Lg Marko

**Comment by yeli69** [comment]
Vielen Dank!
Jetzt ist es wirklich richtig perfekt.
