### ISSUE TITLE
Kann keine Bilder mehr zufügen

### ISSUE THREAD

**Issue by Ricci36** [markocupic/gallery_creator#22]
Plötzlich steht bei allen Alben, wenn ich Bilder zufügen will:
"No upload directory defined in the album settings!"

**Comment by markocupic** [comment]
Hast du beim entsprechenden Album nachgesehen,  ob ein Uploadverzeichnis definiert ist? 
Lg Marko

**Comment by Ricci36** [comment]
Danke Marko!

Nach langem Suchen habe ich auch gefunden, wie man das macht.
Man ist ja darauf fixiert, dass alle Bearbeitungsmöglichkeiten in den
Icons rechts stehen. Also habe ich bei den Alben nach gesucht und nichts
gefunden. Zum Glück tauchte ein Pop-Up auf, als der Cursor über dem
Albumnamen stand, dass half.

Grüße .... Ricci

**Comment by markocupic** [comment]
Trotzdem komisch, dass diese Einstellungen bei dir alle rausgerutscht sind. 
Lg Marko

**Comment by Ricci36** [comment]
4 Bilder auch!

**Comment by markocupic** [comment]
Sind die 4 Dateien vom Server gelöscht worden oder wurde nur deren Datenbank-Eintrag gelöscht?

**Comment by Ricci36** [comment]
Die Datenbankeinträge waren verfälscht - zeigt er ja bei der Reparatur an.
Also statt ..../bild.jpg hieß es plötzlich ..../bild.jpg/bild.jpg - wenn
ich es noch richtig in Erinnerung habe.
