### ISSUE TITLE
Keine Galerie in Newsbeitrag möglich, falsche alias?

### ISSUE THREAD

**Issue by paulharfenmeister** [markocupic/gallery_creator#23]
Hallo,
ich möchte eine Galerie die ich angelegt habe in einem Newsbeitrag anzeigen lassen. Dafür wähle ich im Newsbeitrag als Elementtyp Gallery-Creator-Inhaltselement aus und setze den Haken bei einem Album.

Wenn ich mir den Newsbeitrag im Frontend jetzt anschauen möchte bekomme ich folgende Fehlermeldung und nichts weiter angezeigt:

```
Gallery with alias hier-steht-die-alias-vom-newsbeitrag is either not
 published or not available or you haven't got enough permission to watch it!!!
```

Es scheint, dass hier die News-Alias für die Galerie verwendet wird und natürlich der Eintrag nicht existiert.

Wenn weitere Details benötigt werden, einfach melden.

**Comment by markocupic** [comment]
Lieber Paul
Hier kommt der Ansatz, den gallery_creator verfolgt, nämlich Listenansicht und Detailansicht auf ein und der selben Seite, an seine Grenzen. Ich denke, in diesem Fall bist du mit der Standardgalerie besser beraten. Darf ich fragen, wieso du für einen Newsbeitrag gallery_creator verwenden möchtest?
Liebe Grüsse
Marko

**Comment by paulharfenmeister** [comment]
Hallo Marco,

vielen Dank für die schnelle Reaktion.

Auf unserer Vereinswebseite wollen wir die Bildergalerien an einer Stelle übersichtlich sammeln und gleichzeitig einzelne Alben in den dazugehörigen News verfügbar machen. Wir dachten, dass das funktionieren könnte, jetzt werden wir von dem Newseintrag einfach einen Link zum Album in der Bildergalerie setzen.

Könnte man eventuell vermeiden, dass das Gallery-Creator-Inhaltselement bei den News auswählbar ist, damit andere nicht auch daran scheitern? Ansonsten kann das Issue geschlossen werden.

Sportliche Grüße
Paul

**Comment by markocupic** [comment]
Hallo Paul
Ich hab da was am machen, wenn du noch 2 Tage Geduld hast. Ich habe ein kleines Modul geschrieben, dass es dir möglich machen wird, GalleryCreator-Inhaltselemente in Newsbeiträgen anzuzeigen.
Melde dich mit deiner email, dann sende ich dir das zum Testen.
Liebe Grüsse
Marko

**Comment by Dbzman** [comment]
Hallo Marko,

für unsere Vereinswebseite habe ich eine ähnliche Anforderung..
Es sollte möglich sein ein Album in einem Newsbeitrag anzuzeigen mit dem Vorschaubild als Link zum eigentlichen Album.
Dies wäre eine sehr praktische Funktion, da ich sonst den Umweg über das normale Bild-Element gehen müsste und dort den Link manuell einbinden muss.
Wäre dies mit deinem Ansatz möglich?

Viele Grüße
Timo

**Comment by markocupic** [comment]
Im neusten build der Version 4.9.0 ist diese Möglichkrit eingebaut. Teste das mal.
Lg Marko

**Comment by Dbzman** [comment]
Ich habe das gerade einmal ausprobiert. Hier habe ich jedoch nur die Möglichkeit ein Album in einem Newsbeitrag anzuzeigen, nicht aber zu verlinken.

Viele Grüße
Timo
