### ISSUE TITLE
Template Fehler

### ISSUE THREAD

**Issue by Aiod** [markocupic/gallery_creator#24]
Hi,

Ich vermute einen Fehler im Template.
Ich habe soeben die Version 4.9 über die Contao Packetverwaltung bezogen und danach gleich die bestroffene Seite aufgerufen.
Leider kommt eine weiße Seite und ein Fehler!

Ich habe dann auf Github geschaut und gedacht ich spiele mal dein Template ein. Vllt. hat da was nicht funktioniert. Leider hat es nichts gebracht!

Der Fehler lautet: 
Parse error: syntax error, unexpected end of file in /www/...../contao_update/rr111/system/modules/gallery_creator/templates/ce_gc_default.xhtml on line 138

Vllt. liegts auch einfach an mir :)

**Comment by markocupic** [comment]
Hallo Aiod
Nein, der Fehler liegt nicht an dir. "Irgendwie" hat es  den untersten Teil des Templates abgeschnitten. 
Problem sollte jetzt aber behoben sein.
Liebe Grüsse und besten Dank für die Mitteilung
Marko
