### ISSUE TITLE
Bilder Kommentar

### ISSUE THREAD

**Issue by Aiod** [markocupic/gallery_creator#25]
Hi,

nachdem das letzte Problem behoben wurde, ist der Gallery_creator genau das richtige Werkzeug für mich!
Einen wunsch hätte ich aber noch, bzw. eine anfrage.
Hast du in Planung für einzelne Bilder in einer Gallery Kommentare zu ermöglichen?
Also das man auf ein Bild klickt und unterhalb ein Kommentarfenster bekommt?
Ähnlich wie Facebook und co... 

Vielen Dank für deine Arbeit!

**Comment by markocupic** [comment]
Hallo Aiod
Falls du das Feature als Kleinstauftrag erledigt haben möchtest, dann nimm doch mit mir per email Kontakt auf. Du findest meine Adresse zuoberst im Quelltext in fast jeder Datei meiner Erweiterung.
Liebe Grüsse
Marko
