### ISSUE TITLE
Integration von Filmen (mp4)

### ISSUE THREAD

**Issue by williamsomerset** [markocupic/gallery_creator#27]
Hi.

Ist es auch möglich mit dem Gallery Creator Filme / Clips einzubinden? Unter https://contao.org/de/erweiterungsliste/view/gallery_creator.html ist die Rede von "auch die Anzeige von Filmen über die mediabox ist möglich". Bis jetzt habe ich leider noch nichts in diese Richtung gefunden.

Wenn ich bei einem angelegten Album eine mp4-Datei in das Upload-Feld rein ziehe kommt diese Fehlermeldung "You can't upload files of this type."

Vielen Dank für euer Feedback.

**Comment by markocupic** [comment]
Hallo xxx
Ja, es ist möglich Filme aus dem Dateisystem wiederzugeben. Lade dazu mit dem GalleryCreator Uploader aus dem Backend raus ein Bild hoch, das dir dann als thumbnail dienen wird.
Anschliessend gehst ins entsprechende Album und dann zum entsprechenden Bild. Ganz zu unterst findest du die Möglichkeit einen Film mit dem thumbnail zu verlinken. Alternativ ist auch ein Link zu einem youtube- oder vimeo- Film möglich.
Achtung! Das funktioniert nur mit der Mootools Mediabox. Für die jQuery colorbox sind Anpassungen im template nötig.

Liebe Grüsse
Marko

**Comment by williamsomerset** [comment]
Hi Marko,

danke für die schnelle hilfreiche Antwort. Ich versuche dann mal gleich die fancybox zu installieren, in den Hoffnung, dass dort HTML5 Videos direkt funktionieren. Ich möchte nämlich nicht MooTools verwenden sondern eher jQuery.

Grüße

**Comment by markocupic** [comment]
Oder das Template anpassen. Und dann mit colorbox...
Lg Marko
