### ISSUE TITLE
wrong contao/core minimum requirement for version 5.0.0

### ISSUE THREAD

**Issue by fritzmg** [markocupic/gallery_creator#28]
Version `5.0.0` for this extension uses the `Contao\StringUtil` class. This class is only available from Contao `3.5.1` and up. However, the `composer.json` and the release in the [extension repository](https://contao.org/de/erweiterungsliste/view/gallery_creator.50000009.de.html) lists `"contao/core":">=3.4,<4"` as a requirement, instead of `"contao/core":">=3.5.1,<4"` for example.

See also https://community.contao.org/de/showthread.php?22634-gallery_creator&p=401438&viewfull=1#post401438

**Comment by markocupic** [comment]
fixed in https://github.com/markocupic/gallery_creator/commit/ce1e3ffdc67b23f17434ea612b3473d540d57502
