### ISSUE TITLE
Konfigurationseinstellung "Sortieren nach" wird nicht gespeichert

### ISSUE THREAD

**Issue by zonky2** [markocupic/gallery_creator#31]
sollte in
https://github.com/markocupic/gallery_creator/blob/345120dd579c6ec34339f4627824c8dacb8a6a2b/dca/tl_gallery_creator_albums.php#L1414

nicht 
```diff
        // return default value
-        return 'custom';
+        return $varValue;
```
stehen?

**Comment by markocupic** [comment]
Hallo zonky
Das mag auf den ersten Blick etwas verwirrend zu sein. Diese Funktion dient, dazu die Bilder eines Albums neu zu sortieren. Möchtest du die Bilder beispielsweise nach dem Dateinamen sortieren wählst du die Einstellung und klickst den Speichern Button. 
Die Bilder erhalten jetzt alle im Feld sorting einen neuen Wert. Das Select Menu wechselt dann wieder auf custom.

**Comment by zonky2** [comment]
das ist in der Tat verwirrend - zumal man nicht erkennen kann, wie die Dateien sortiert sind...

wenn in der DB der letzte Sortierstatus eingespeichert wird - und nicht immer nur "custom" - könnte man das ggf. bei den Dateien anzeigen - i.E. "Aktuelle Sortierung: Datum Aufsteigend"

**Comment by markocupic** [comment]
Nur ist die ganze Sortierung dahin, wenn du weitere Bilder hochlädst. Diese werden nämlich schön am Ende einsortiert.

**Comment by zonky2** [comment]
verstehe ich das richtig?

Die Sortierung für die FE-Ausgabe wird im CE gemacht - außer man aktiviert die (manuelle) Sortierung und dann wird die in der Konfig eingestellten Sortierung verwendet.

Die Sortierung in der Konfig bezieht sich immer auf eine manuelle Sortierung aber man kann sich die Dateien "vor-sortieren" lassen z.B. nach Datum...

... wenn das richtig, ist es doch logisch, dass neue Dateien "hinten anstehen" - wenn ich z.B. 200 Bilder manuell sortiert habe und 10 hinzu kommen und dann erstmal auf "Sortiere nach Dateiname" klicke, muss ich 210 Dateien (neu) sortieren statt nur der 10 neuen... oder?

**Comment by markocupic** [comment]
Habe die Select Menu Überschrift und die option custom etwas umbenannt, so dass die Verwirrung nun etwas kleiner sein sollte.
