### ISSUE TITLE
Individuelle Sortierung sollte nur möglich sein, wenn Select entsprechend ausgewählt

### ISSUE THREAD

**Issue by zonky2** [markocupic/gallery_creator#32]
btw:: wofür sind die Radiobuttons bei den Thumbnails in der Konfig?

**Comment by markocupic** [comment]
Falls der Bilddatensatz existiert, das Bild dazu irrtümlicherweise vom Server gelöscht wurde, käme anstatt des thumbnails nichts. Natürlich mit negativen Folgen für das Layout. Wenn du hier ein Thumbnail definiert, kommt an dieser Stelle dafür das Ersatz-Thumbnail. 
Z.B.: 
https://speckycdn-sdm.netdna-ssl.com/wp-content/uploads/2010/03/four-oh-four_21.jpg
Liebe Grüsse
Marko

**Comment by zonky2** [comment]
>Falls der Bilddatensatz existiert, das Bild dazu irrtümlicherweise vom Server gelöscht wurde, käme anstatt des thumbnails nichts.

... und dafür die Radiobuttons?

**Comment by markocupic** [comment]
Ich glaube, wir reden nicht vom Gleichen. Welche radiobuttons meinst du? Kannst du mal einen Screenshot posten?

**Comment by zonky2** [comment]
![shot208](https://cloud.githubusercontent.com/assets/1045318/15239631/6d87823a-18e4-11e6-9765-65a92d55271e.jpg)

**Comment by markocupic** [comment]
ach so...
Mit Konfig meinte ich die Settings im Modul (Backend-Einstellungen).
Die Thumbnails oben mit den Radios dienen dazu das Vorschau Thumbnail auszuwählen, das für das entsprechende Album in der Albumauflistung im FE angezeigt werden soll. Angenehmer NEbeneffekt: Mit "Drag and Drop" kannst du die auch noch gleich erledigen. Das ist sehr praktisch, da du die Thumbnails auch gleich alle schön vor dir hast.

**Comment by zonky2** [comment]
ahh... o.k. - ggf. im Erklärungstext "Album-Vorschaubild per Radiobutton auswählen; Elemente können für individuelle Sortierung durch ziehen umsortiert werden."

bezüglich der Frage, ob die Sortiermöglichkeit nur bei "custom" möglich sein sollte, wäre wahrscheinlich das Posting https://github.com/markocupic/gallery_creator/issues/31#issuecomment-218887196 "zuständig"
