### ISSUE TITLE
Contao 4.3 - Fehler bei Aktualisierung der DB in install.php

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery_creator#36]
Hallo,

bei der Installation der gallery unter Contao 4.3 kommt es nach Aufruf des Install-Tools bei der Aktualisierung der Datenbank zu nachfolgendem Fehler:
```
app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): 
An exception occurred while executing 'CREATE TABLE tl_gallery_creator_albums ...
... DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = 
MyISAM':\n\nSQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'alias' used 
in key specification without a key length at /Users/georg/Sites/Luetten-
Dieks_4.3/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException(code: 
42000): SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'alias' used in 
key specification without a key length at /Users/georg/Sites/Luetten-
Dieks_4.3/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:801)"} []
```

**Comment by markocupic** [comment]
Hallo Seefahrer
Ich konnte den Fehler bei meiner Testinstallation nicht nachstellen. Kann deshalb über sehr wage auf den Fehler schliessen. Bitte lade dir mal die Version vom hotfix-branch runter und teste es bei dir nochmals.
https://github.com/markocupic/gallery_creator/tree/hotfix

Liebe Grüsse
Marko

**Comment by Seefahrer** [comment]
Hallo Marko,
habe ich probiert, leider ein ähnlicher Fehler:
`SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'uuid' used in key specification without a key length at /Users/georg/Sites/Luetten-Dieks_4.3/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:801)"} []`

Einen schönen 4. Advent wünscht Dir
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,
wenn ich den Index 'uuid' aus dem sql-Statement entferne, klappt es, aber dann funktioniert wahrscheinlich etwas anderes nicht mehr?

Der Fehler tritt auch auf, wenn ich das sql-Statement direkt in phpadmin ausführe ...

**Comment by Seefahrer** [comment]
Durch Angabe einer keylength von 255 characters (utf-8) wird die Tabelle ohne Fehler erzeugt ...
 ... INDEX uuid (uuid(255)), ...

**Comment by markocupic** [comment]
Lieber Georg
Danke für deine Forschungsarbeit. Eigentlich ist der key hier überflüssig. Ich habe ihn entfernt. 
Würdest du nochmals mit dem hotfix-branch testen?
https://github.com/markocupic/gallery_creator/tree/hotfix
Liebe Grüsse und auch dir noch eine schöne Adventszeit.
Marko

**Comment by Seefahrer** [comment]
Lieber Marko,
die Installation klappt jetzt ohne Probleme! Vielen Dank! Und auch vielen Dank für Deine Erweiterung, die die uns kostenlos zur Verfügung stellst! Btw, hast Du geplant, Gallery Creator irgendwann auch als Symfony bundle für Contao >=4 zur Verfügung zu stellen? Habe meine Alben (ca. >5000 Bilder) bisher mit Photoalbum2 auf meiner Seite.  PA2 hängt allerdings von 3 weiteren Erweiterungen ab, eine Lösung mit einer zudem lebhaft gepflegten "Single-Extension" käme mir da sehr gelegen.
Liebe Grüße auch von meiner Seite
Georg

**Comment by Seefahrer** [comment]
Hallo noch einmal Marko,
habe gerade bemerkt, dass das Einlesen der Bilder aus Verzeichnissen in die GC Verzeichnisse nicht klappt. Ich muss statt der Verzeichnisse die Bilder einzeln auswählen, erst dann klappt es.

**Comment by markocupic** [comment]
Hallo Georg
Hast du eventuell versucht Bilder einzulesen, die bereits im entsprechenden Album drin sind. Bilder die bereits im Album drin sind werden gefiltert. Neue Bilder sollten dagegen schon importiert werden, du brauchst nur den übergeordneten Ordner anzuwählen.
Probier mit der aktuellen hotfix-Version.
Liebe Grüsse
Marko

**Comment by markocupic** [comment]
Hallo Georg
GalleryCreator ist nun als bundle für Contao >=4.3 verfügbar:
https://github.com/markocupic/gallery-creator-bundle
Liebe Grüsse
Marko

**Comment by Seefahrer** [comment]
Hallo Marko,
Das ist ja prima, probier ich nach den Feiertagen gleich aus. Wird das mittels composer require abgerufen?
Ein schönes Weihachtsfest wünscht Dir
Georg


Von meinem iPad gesendet

**Comment by markocupic** [comment]
Hallo Georg
Ja, genau:
composer require markocupic/gallery-creator-bundle:~1.0

Bin froh, wenn du das mal durchtestest und mir bei Fehlern wieder Feedback gibst.
Frohe Weihnachten und liebe Grüsse
Marko

**Comment by Seefahrer** [comment]
Hallo Marko,

ich brech mir gerade die Zunge und Finger hinsichtlich des Eintrags in der AppKernel.php.
Kannst Du mir da weiterhelfen?

Danke und noch ein schönes Restfest
Georg

**Comment by markocupic** [comment]
Hallo Georg
Ich würde dagen so:

new Markocupic\GalleryCreatorBundle\MarkocupicGalleryCreatorBundle(),

Liebe Grüsse
Marko

**Comment by Seefahrer** [comment]
Hallo Marko,

das klappt … und ich war mir sicher, das genauso auch schon versucht zu haben … hmmmm …

Liebe Grüße
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,

so auf den ersten Blick klappen Installation, Registrierung im Kernel, Einrichten der Galerien, uploaden der Bilder etc. perfekt!!!
Bleibt nur noch, die Ausgabe per css zweispaltig zu formatieren. Hast Du da was vorbereitet? Ansonsten mache ich das selbst.
Werde in den nächsten Tagen meine Bilder mit Deiner Galerie auf Deiner Seite veröffentlichen. Sollte ich dabei auf Fehler stoßen, werde ich Dich das wissen lassen.

Nochmals liebe Grüße von der stürmischen Nordseeküste
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,

hab die Klasse col_2 entdeckt womit die zweispaltige Galerieansicht kein Problem mehr ist.
Die zweispaltige Ansicht der Übersicht der Untergalerien kriege ich auch noch hin :)

Liebe Grüße
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,

ich weiss jetzt, woran es lag, dass der Eintrag in der AppKernel.php ungültig war: Ich hatte bei der Kombi aus Namespace und Class versehentlich Deinen Namen in Camelcases geschrieben …
Nun ja, jetzt klappt es ja.
Ich würde gerne ein kleine Anpassung vornehmen:
1. Übersicht der Alben zweispaltig
2. Bei Klick auf ein Album soll nicht auf das Unteralbum verzweigt werden, sondern die Bilder des jeweiligen Albums gleich in der Lightbox (jquery Colorbox) geöffnet werden. 

Meine Versuche, Dein css zu bewegen, die Albenübersicht zur zweispaltigen Anzeige zu bewegen, sind leider gescheitert. „..gallery_creator .list_albums li {float: left} klappt auch nicht …
Erst wenn ich in .gallery_creator .list_albums .level_1 den Wert für width auf z.B. 30% setze wird die Übersicht 2-spaltig angezeigt, leider in der halben zur Verfügung stehenden Restfläsche …
(de facto vierspaltig).
Wie Du siehst bin ich nicht so der php und css Experte, die Anpassung Deines templates „ce_gc_default.html5“ klappt auch nicht so recht …

Vielleicht kann Du mir ein wenig zur Seite stehen?
Liebe Grüße - Georg

**Comment by markocupic** [comment]
Hallo Georg
Bin gerade etwas busy. 
Ich habe dir ein gist angefertigt für dein Colorbox anliegen. Lege dieses template ins templates Verzeichnis und wähle es in den Inhaltselementeinstellungen aus. 
Unbedingt vorher noch auf gallery_creator_bundle 1.0.1 updaten. 

https://gist.github.com/markocupic/327413038262b2f84171f8df177cf021

Liebe Grüsse 

Marko

PS: Sende mir doch deinen Layout-Wunsch als Entwurf in Form eines Worddokuments auf meine E-Mail-Adresse. Dann können wir via diesen Kanal weiterkommunizieren, m.cupic@gmx.ch

**Comment by Seefahrer** [comment]
Hallo Marko,

find ich richtig prima von Dir, so ein template mal eben aus dem Ärmel zu schütteln und mir zur Verfügung zu stellen.
Viele Dank dafür! Eine kleinigkeit ist mir aufgefallen: Wenn ich in der Albenübersicht den Mauszeiger über das Bild bewege, um zu klicken, bleibt der Mauszeiger ein Pointer und ändert sich nicht in das bekannte Handsymbol.
Wahrscheinlich nur eine Kleinigkeit, die Dir leicht fällt …

Nochmals vielen Dank, einen guten Rutsch und liebe Grüße
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,

find ich richtig prima von Dir, so ein template mal eben aus dem Ärmel zu schütteln und mir zur Verfügung zu stellen.
Viele Dank dafür! Eine kleinigkeit ist mir aufgefallen: Wenn ich in der Albenübersicht den Mauszeiger über das Bild bewege, um zu klicken, bleibt der Mauszeiger ein Pointer und ändert sich nicht in das bekannte Handsymbol.
Ebenfalls Blur-Effekt und ‚+‘ - Zeichen fehlen ... 
Wahrscheinlich nur eine Kleinigkeit, die Dir leicht fällt …

Nochmals vielen Dank, einen guten Rutsch und liebe Grüße
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,

den blur-Effekt etc. kriege ich mit nachfolgendem CSS hin, leider hat der Cursor-Style keine Auswirkung ...

.list_albums .col_1 .image_container:hover {
    -webkit-filter: blur(2px);
	-moz-filter: blur(2px);
	filter: blur(2px);
	-webkit-transform: scale(1.05);
	-moz-transform: scale(1.05);
	-ms-transform: scale(1.05);
	-o-transform: scale(1.05);
	transform: scale(1.05);
}
.list_albums .col_1 .image_container:hover:after {
    	font: 1.5em/1 "RockSolid Icons";
	content: "\2b";
    	cursor: pointer;
	display: inline-block;
	position: absolute;
	top: 50%;
	left: 50%;
	color: #fff;
	text-shadow: 0 0 2px rgba(0, 0, 0, 0.35);
}

Liebe Grüße
Georg

**Comment by Seefahrer** [comment]
Hallo Marko,

habe vor der Click-Function im template nachfolgende Zeile eingefügt, jetzt klappt alles!

 $('.list_albums figure.image_container').css( 'cursor', 'pointer' );

Liebe Grüße
Georg

**Comment by schmanat** [comment]
Hallo @Seefahrer, dass ist natürlich eine Möglichkeit, ich würde dir aber empfehlen genau diese Zeile ins CSS zu schreiben, macht ja keinen Sinn hierfür extra JS zu bemühen

```
.list_albums figure.image_container {
    cursor: pointer
}
```

**Comment by Seefahrer** [comment]
gesagt, getan …

**Comment by markocupic** [comment]
Hallo Georg
Mit dem url-Parameter "page" habe ich nicht gerechnet. Ich habe das gist angepasst. Wenn du das template schon angepasst hast, brauchst du nur den script-Block zu übernehmen. Danach sollte es laufen.

https://gist.github.com/markocupic/327413038262b2f84171f8df177cf021

Liebe Grüsse 

Marko

**Comment by Seefahrer** [comment]
Hallo Marko,

jetzt ist es perfekt, herzlichsten Dank dafür!!! Unsere 4 „Enten“ (Entlebucher Sennenhunde) bedanken sich ebenfalls!
Werde jetz tauch meine anderen Galerien auf Deine Extension umstellen.

Ein gutes und gesundes neues Jahr wünsche ich Dir
Liebe Grüße
Georg

**Comment by markocupic** [comment]
Hallo Georg
Du, ich habe die Erweiterung noch etwas umgebaut. Falls du ein Update auf >= 1.0.3 machst, solltest du im Template auch noch einmal den <script> Block anpassen. Sorry! Dadurch ist der Code universeller einsetzbar, 
https://gist.github.com/markocupic/327413038262b2f84171f8df177cf021

Übrigens, wohne ich keine 10 km vom Entlebuch entfernt. Die Hunde sind mir bestens bekannt ;-)
Liebe Grüsse und ein gute Zeit

Marko

**Comment by Seefahrer** [comment]
Hallo Marko,

hast Du eine Idee (klar hast Du eine …), wie ich in der j_colorbox (lLightgbox) eine Bildunterschrift hineinbekomme?
Ich verwende Dein template wie im Anhang …

Liebe Grüße
Georg
