### ISSUE TITLE
mehrere Gallery Creator Elemente im Artikel

### ISSUE THREAD

**Issue by pbd-kn** [markocupic/gallery_creator#38]
Hi,
wenn ich mehrere Gallery Creator Elemente in einem Aritkel habe, wird immer nur eines angezeigt.
Wie knn ich das umgehen ?

**Comment by pbd-kn** [comment]
Der Fehler tritt nur auf, wenn auf dieser Seite das Flag
 Weiterleitung bei einzelnem Album
geetzt ist,
und in einem Element existiert nur ein Album.
Dann werden die anderen nicht angezeigt

**Comment by markocupic** [comment]
Du kannst auf die [dev-2er ](https://github.com/markocupic/gallery-creator-bundle/tree/dev-2.0)Version von gallery-creator-bundle updaten. Aber Vorsicht! Alte evtl. vorhandene Custom templates musst du neu schreiben. Es gabe grosse Änderungen im Code, weil jahrelange Altlasten abgestossen wurden.
